version: "{build}"

# Source Config
clone_folder: c:\gopath\src\github.com\amitsaha\gitbackup

# Build host

environment:
  GOPATH: c:\gopath
  matrix:
    - environment:
      GOVERSION: 1.7.5
    - environment:
      GOVERSION: 1.8

# Build

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin;%Path%
  - go version
  - go env

build: off


test_script:
  - cd c:\gopath\src\github.com\amitsaha\gitbackup
  - set gopath=c:\gopath\src\github.com\amitsaha\gitbackup\vendor;%gopath%
  - go build -o bin\gitbackup.exe src\gitbackup\main.go src\gitbackup\client.go src\gitbackup\backup.go src\gitbackup\repositories.go
  - ls bin\
  - cd src\gitbackup\
  - go test -v
